### ISSUE TITLE
On linux, instance of systemIdle is not created at first time

### ISSUE THREAD

**Issue by snehalteli** [unitedideasco/system_idle#8]
On linux, instance of systemIdle is not created at first time. when application runs at second time then it reflecting at 1st window..

**Comment by Levi-Lesches** [comment]
Hi! Can you try again with the latest `main` branch? Add the following file: 

```yaml
# pubspec_overrides.yaml

dependency_overrides:
  system_idle: 
    git: https://github.com/unitedideasco/system_idle.git
```
